### ISSUE TITLE
Несовместимость c ReportPlus

### ISSUE THREAD

**Issue by bladbl** [Leymooo/BungeeCord#40]
Очень странная ошибка вылазит. Версия ботфильтра крайня. На последней waterfall такого не наблюдаю.
```01:30:56 [SEVERE]     at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
01:30:56 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
01:30:56 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
01:30:56 [SEVERE]     at java.lang.Thread.run(Thread.java:748)
01:30:56 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@e260766, id=17, owner=me.lucko.luckperms.bungee.LPBungeeBootstrap@2f7a7219, task=me.lucko.luckperms.bungee.listeners.BungeeConnectionListener$$Lambda$278/436039416@467bfc3, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException
    at me.lucko.luckperms.bungee.listeners.BungeeConnectionListener.lambda$onPlayerLogin$0(BungeeConnectionListener.java:97)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
01:31:00 [INFO] [/92.38.73.147:5480] <-> InitialHandler has connected
01:31:00 [INFO] [/92.38.73.147:5481] <-> InitialHandler has connected
01:31:01 [INFO] [rheaboam] <-> InitialHandler has connected
01:31:01 [INFO] [rheaboam] <-> InitialHandler has connected
01:31:01 [SEVERE] [LuckPerms] Exception occurred whilst loading data for 95cbc3d2-2595-302b-b6a3-3086e3521e63 - rheaboam
01:31:01 [SEVERE] java.lang.NullPointerException
01:31:01 [SEVERE]     at me.lucko.luckperms.common.plugin.util.AbstractConnectionListener.loadUser(AbstractConnectionListener.java:67)
01:31:01 [SEVERE]     at me.lucko.luckperms.bungee.listeners.BungeeConnectionListener.lambda$onPlayerLogin$0(BungeeConnectionListener.java:84)
01:31:01 [SEVERE]     at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
01:31:01 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
01:31:01 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
01:31:01 [SEVERE]     at java.lang.Thread.run(Thread.java:748)
01:31:01 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@e260766, id=21, owner=me.lucko.luckperms.bungee.LPBungeeBootstrap@2f7a7219, task=me.lucko.luckperms.bungee.listeners.BungeeConnectionListener$$Lambda$278/436039416@4bee66a4, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException
    at me.lucko.luckperms.bungee.listeners.BungeeConnectionListener.lambda$onPlayerLogin$0(BungeeConnectionListener.java:97)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by bladbl** [comment]
Думаю если пересобрать на более свежем билде, проблема отпадет.
