### ISSUE TITLE
Couldn't register custom payload // Invalid payload REGISTER!

### ISSUE THREAD

**Issue by danirod12** [Leymooo/BungeeCord#86]
```
[16:36:00 ERROR]: Couldn't register custom payload
org.bukkit.plugin.messaging.ChannelNameTooLongException: Attempted to send a Plugin Message to a channel that was too large. The maximum length a channel may be is 64 chars (attempted 85 - 'rp:pluginsr:messagechannelsr:skinchangeadvancedban:mainbungeecord:mainunitedmine:auth.
        at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:500) ~[patched_1.16.5.jar:git-Paper-775]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.addChannel(CraftPlayer.java:1630) ~[patched_1.16.5.jar:git-Paper-775]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:3054) ~[patched_1.16.5.jar:git-Paper-775]
        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44) ~[patched_1.16.5.jar:git-Paper-775]
        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.16.5.jar:git-Paper-775]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-775]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-775]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-775]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-775]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-775]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-775]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-775]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-775]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[patched_1.16.5.jar:git-Paper-775]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Paper-775]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-775]
        at java.lang.Thread.run(Thread.java:832) [?:?]
[16:36:00 INFO]: TheDevilArtY lost connection: Invalid payload REGISTER!
```

На BotFilter ошибки нет (Есть флаг -Dbotfilter.printallerrors=true). На подсервере ошибка, описанная выше

Проверил с Waterfall 445, все работает. Ошибка появилась после версии BotFilter 3.8.7, на 3.8.7 все работало.
Ошибка возникает при входе клиента любой версии (Проверено на 1.17.1 и 1.16.5)

Кикает по причине "Потеряно соединение с серверов"

**Comment by danirod12** [comment]
На 3.8.8 все работает
На 3.8.8.1 ошибка такая

**Comment by Leymooo** [comment]
между 8 и 8.1 нету никаких изменений, которые могли бы на это повлиять. мне кажется что это либо из-за клиента, либо изза какогото плагина на банжи или спиготе

**Comment by danirod12** [comment]
Как это возможно тогда? Клиент и плагины одинаковые. Изменилась только версия банжи...

**Comment by loperd** [comment]
![image](https://user-images.githubusercontent.com/23015901/126066346-8c9f5caf-250d-4ffa-85b0-e4f1e483896b.png)
офни advancedbans и попробуй снова

**Comment by danirod12** [comment]
> ![image](https://user-images.githubusercontent.com/23015901/126066346-8c9f5caf-250d-4ffa-85b0-e4f1e483896b.png)
> офни advancedbans и попробуй снова

Ошибка не меняется. Размер меньше только пишет

64 требуется (получено 69) вроде
