### ISSUE TITLE
[SEVERE] Exception in thread "main" 

### ISSUE THREAD

**Issue by wilddip** [Leymooo/BungeeCord#90]
On startup

```18:09:06 [SEVERE] Exception in thread "main" 
18:09:06 [SEVERE] java.lang.reflect.InaccessibleObjectException: Unable to make private native java.lang.reflect.Field[] java.lang.Class.getDeclaredFields0(boolean) accessible: module java.base does not "opens java.lang" to unnamed module @50828c64
18:09:06 [SEVERE]     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
18:09:06 [SEVERE]     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
18:09:06 [SEVERE]     at java.base/java.lang.reflect.Method.checkCanSetAccessible(Unknown Source)
18:09:06 [SEVERE]     at java.base/java.lang.reflect.Method.setAccessible(Unknown Source)
18:09:06 [SEVERE]     at ru.leymooo.botfilter.config.Config.setAccessible(Config.java:371)
18:09:06 [SEVERE]     at ru.leymooo.botfilter.config.Config.getField(Config.java:258)
18:09:06 [SEVERE]     at ru.leymooo.botfilter.config.Config.set(Config.java:54)
18:09:06 [SEVERE]     at ru.leymooo.botfilter.config.Config.set(Config.java:114)
18:09:06 [SEVERE]     at ru.leymooo.botfilter.config.Config.load(Config.java:99)
18:09:06 [SEVERE]     at ru.leymooo.botfilter.config.Settings.reload(Settings.java:60)
18:09:06 [SEVERE]     at ru.leymooo.botfilter.BotFilter.<init>(BotFilter.java:74)
18:09:06 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:282)
18:09:06 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:49)
18:09:06 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)```

**Comment by Leymooo** [comment]
Для запуска на новых версиях Java (Java 16+) добавьте эти флаги в строку запуска перед -jar:
`--illegal-access=permit` (не будет на java 17+)
или
`--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED`  (должно работать на всех версиях)
